name: Docker Hub

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dkaoster/nodejs-chrome-selenium
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
