name: Docker Hub

on:
  push:
    branches:
      - master
  schedule:
    # Run every Sunday at 00:00
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build and Publish Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: dkaoster/nodejs-chrome-selenium
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
